dist: bionic
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    #- PATH=/opt/python/3.7.1/bin:$PATH
script:
  - which python
  - which pyenv
  - pyenv versions
  - pyenv global 3.7.1
  - python -VV
  - pip -V
  - pip install --user awscli
