dist: xenial
script:
  - pyenv global 3.7.1 system
  - which pip
  - pip --version
  - which python3
  - python3 -VV
  - which pip3
  - pip3 --version
  - pip3 install awscli
  - which aws
  - aws version
